# Project-wide Gradle settings

# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE are ignored when building from the
# command line, check build.gradle for more details.

# For more details on how to configure your build environment visit
# https://www.gradle.org/configure-gradle

# Enables namespacing of each library's R class so that its R class includes only the
# resources declared in the library itself and does not include a R class or internal
# R classes from its dependencies.
android.nonTransitiveRClass=true

# Gradle memory settings

# Enable daemon
org.gradle.daemon=true

# Enable parallel builds
org.gradle.parallel=true

# Version definitions
minSdkVersion=24
targetSdkVersion=34
compileSdkVersion=34
kotlinVersion=1.9.10
