name: Clean Android Project

on:
  workflow_dispatch:
  push:

jobs:
  clean:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant permissions
        run: chmod +x gradlew

      - name: Clean Gradle project
        run: ./gradlew clean

      - name: Delete additional caches
        run: |
          rm -rf ~/.gradle/caches
          rm -rf ~/.gradle/daemon
          rm -rf .gradle
          rm -rf build
          rm -rf app/build

      - name: Verify clean build
        run: ./gradlew assembleDebug